# Generated by Django 4.2 on 2024-10-24 01:23

import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='filepath',
            field=models.FilePathField(path=db.models.documents_path, recursive=True),
        ),
    ]
