# Generated by Django 4.2 on 2024-10-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_page_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.IntegerField(choices=[(0, 'Processing'), (1, 'Ready')], default=0),
        ),
    ]
