# Generated by Django 4.2 on 2024-10-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.IntegerField(choices=[(0, 'Processing'), (1, 'Ready'), (2, 'Error')], default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.IntegerField(choices=[(0, 'Processing'), (1, 'Ready'), (2, 'Error')], default=0),
        ),
    ]
