# Generated by Django 4.2 on 2024-10-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_page_status_alter_document_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='contents_summary',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='page',
            name='contents_summary',
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
