# Generated by Django 4.2 on 2024-10-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_rename_contents_summary_document_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='error_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
