# Generated by Django 4.2 on 2024-10-26 11:29

from django.db import migrations
import pgvector.django.indexes
import pgvector.django.vector
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_user'),
    ]

    operations = [
        VectorExtension(),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['document', 'number']},
        ),
        migrations.AddField(
            model_name='page',
            name='description_embeddings',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='summary_embeddings',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='text_embeddings',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddIndex(
            model_name='page',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['text_embeddings'], m=16, name='text_embeddings_index', opclasses=['vector_l2_ops']),
        ),
        migrations.AddIndex(
            model_name='page',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['description_embeddings'], m=16, name='description_embeddings_index', opclasses=['vector_l2_ops']),
        ),
        migrations.AddIndex(
            model_name='page',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['summary_embeddings'], m=16, name='summary_embeddings_index', opclasses=['vector_l2_ops']),
        ),
    ]
