# Generated by Django 4.2 on 2024-10-27 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_enable_trigram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False),
        ),
    ]
