# Generated by Django 4.2 on 2024-10-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_alter_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Pdf'), (2, 'Image'), (3, 'Text')], default=0),
        ),
    ]
