# Generated by Django 4.2 on 2024-10-28 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_alter_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
