# Generated by Django 4.2 on 2024-10-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_document_time_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-time_created']},
        ),
    ]
