# Standalone Certbot for initial certificate generation
services:
  certbot:
    image: certbot/certbot
    entrypoint: /bin/sh -c 'certbot certonly --standalone --non-interactive --agree-tos -m "<FILL IN EMAIL>" -d "<FILL IN DOMAIN NAME>"
    env_file:
      - ../dockerenv
    volumes:
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80" # Required to complete the challenge on the initial run
