# Standalone Certbot for initial certificate generation
services:
  certbot:
    image: certbot/certbot
    command: certonly --standalone --non-interactive --agree-tos -m "$${CERTBOT_EMAIL}" -d "$${DOMAIN_NAME}"
    env_file:
      - ../dockerenv
    volumes:
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80" # Required to complete the challenge on the initial run
